name: Bin WhatsApp notifier

on:
  # Daily at 17:00 UTC (18:00 UK in summer, 17:00 in winter)
  schedule:
    - cron: "0 17 * * *"
  # Let you run it on demand too
  workflow_dispatch:
    inputs:
      json_url:
        description: "Override JSON URL (optional)"
        required: false
        default: ""

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send WhatsApp if tomorrow is a collection day
        env:
          BIN_JSON_URL: ${{ github.event.inputs.json_url || 'https://jackberryman.github.io/plymouth-bin-scraper/PL6_5HX_72_Windermere.json' }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}   # e.g. whatsapp:+14155238886
          TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}       # e.g. whatsapp:+447969513470
        run: python notify.py
